packages:
  - "."

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - "@kayord/ui"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

patchedDependencies:
  "@tanstack/svelte-store@0.12.1": patches/@tanstack__svelte-store@0.12.1.patch
