services:
  traefik:
    image: traefik:v3
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./container/traefik/certs:/certs:ro"
      - "./container/traefik/config:/config:ro"

  postgres:
    build: ./container/db
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_DB: club
      POSTGRES_USER: club
      POSTGRES_PASSWORD: club
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    command: |
      postgres
      -c shared_preload_libraries=pg_stat_statements,pg_cron
      -c wal_level=replica
      -c hot_standby=on
      -c shared_buffers=512MB
      -c maintenance_work_mem=128MB
      -c effective_io_concurrency=2
      -c min_wal_size=1GB
      -c max_wal_size=3GB

  redis:
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: club
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save 60 1
      --appendonly yes
      --appendfsync everysec
      --requirepass club

  aspire-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    restart: unless-stopped
    ports:
      - 18888:18888
      - 18889:18889

  keycloak:
    build: ./container/keycloak
    restart: unless-stopped
    environment:
      KC_HOSTNAME: https://auth.localhost
      KC_PROXY: traefik
      # KC_PROXY_HEADERS: xforwarded
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: club
      KC_DB_PASSWORD: club
      KC_HTTP_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
  redis:
  mailpit:
