/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const AccountSyncBody = zod.object({
	force: zod.boolean(),
});

export const AccountSyncResponse = zod.void();

export const AccountSessionResponseItem = zod.object({
	id: zod.string().nullish(),
	ipAddress: zod.string().nullish(),
	lastAccess: zod.int().nullish(),
	start: zod.int().nullish(),
	username: zod.string().nullish(),
});
export const AccountSessionResponse = zod.array(AccountSessionResponseItem);

export const AccountSessionRevokeAllResponse = zod.void();

export const AccountSessionRevokeBody = zod.object({
	id: zod.string(),
});

export const AccountSessionRevokeResponse = zod.void();

export const AccountRoleParams = zod.object({
	facilityId: zod.int(),
});

export const AccountRoleResponseItem = zod.object({
	facilityId: zod.int().nullish(),
	normalizedName: zod.string().nullish(),
});
export const AccountRoleResponse = zod.array(AccountRoleResponseItem);

export const AccountCredentialResponse = zod.object({
	isTwoFactorEnabled: zod.boolean(),
	hasCredential: zod.boolean(),
});

export const AccountCredentialDisableTokenResponse = zod.void();

export const AccountCredentialDisableBody = zod.object({
	token: zod.string(),
});

export const AccountCredentialDisableResponse = zod.void();
