/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const BookingUpdateStatusBody = zod.object({
	bookingId: zod.int(),
	status: zod.union([zod.literal(1), zod.literal(2), zod.literal(3), zod.literal(4)]),
});

export const BookingUpdateStatusResponse = zod.void();

export const BookingUpdateParams = zod.object({
	id: zod.int(),
});

export const BookingUpdateBody = zod.object({
	bookings: zod.array(
		zod.object({
			slotId: zod.string(),
			slotContractId: zod.int(),
			name: zod.string().nullish(),
			email: zod.string().nullish(),
			cellphone: zod.string().nullish(),
		})
	),
	extras: zod.array(
		zod.object({
			extraId: zod.int(),
			amount: zod.int(),
		})
	),
});

export const BookingUpdateResponse = zod.void();

export const BookingGetParams = zod.object({
	id: zod.int(),
});

export const BookingGetResponse = zod.object({
	id: zod.int(),
	bookingStatusId: zod.int(),
	bookingStatus: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	bookingStatusDate: zod.iso.datetime({ offset: true }),
	userId: zod.string().nullish(),
	user: zod
		.object({
			firstName: zod.string(),
			lastName: zod.string(),
			picture: zod.string().nullish(),
		})
		.nullish(),
	isPaid: zod.boolean(),
	amountOutstanding: zod.number(),
	amountPaid: zod.number(),
	expiresAt: zod.iso.datetime({ offset: true }),
	slotContractBookings: zod.array(
		zod.object({
			id: zod.int(),
			slotContractId: zod.int(),
			slotContract: zod.object({
				id: zod.int(),
				slotId: zod.string(),
				slot: zod.object({
					id: zod.string(),
					resourceId: zod.int().nullish(),
					facilityId: zod.int().nullish(),
					startDatetime: zod.iso.datetime({ offset: true }),
					endDatetime: zod.iso.datetime({ offset: true }).nullish(),
					maxBookings: zod.int(),
				}),
				contractId: zod.int(),
				contractName: zod.string().nullish(),
				price: zod.number(),
				validationId: zod.int().nullish(),
				canPayLater: zod.boolean(),
				description: zod.string().nullish(),
			}),
			bookingId: zod.int(),
			userId: zod.string().nullish(),
			name: zod.string().nullish(),
			email: zod.string().nullish(),
			cellphone: zod.string().nullish(),
		})
	),
	extraBookings: zod.array(
		zod.object({
			extraId: zod.int(),
			extra: zod.object({
				id: zod.int(),
				facilityId: zod.int(),
				outletId: zod.int(),
				name: zod.string(),
				code: zod.string(),
				price: zod.number(),
			}),
			bookingId: zod.int(),
			amount: zod.int(),
		})
	),
});

export const BookingGetUserQueryParams = zod.object({
	sorts: zod.string().nullish(),
	filters: zod.string().nullish(),
	page: zod.int().nullish(),
	pageSize: zod.int().nullish(),
});

export const BookingGetUserResponse = zod.object({
	items: zod.array(
		zod.object({
			id: zod.int(),
			bookingStatusId: zod.int(),
			bookingStatusName: zod.string(),
			bookingStatusDate: zod.iso.datetime({ offset: true }),
			facilityName: zod.string().nullish(),
			slotStartDatetime: zod.iso.datetime({ offset: true }).nullish(),
			slotEndDatetime: zod.iso.datetime({ offset: true }).nullish(),
			playerCount: zod.int(),
			amountOutstanding: zod.number(),
			amountPaid: zod.number(),
			isPaid: zod.boolean(),
			expiresAt: zod.iso.datetime({ offset: true }),
		})
	),
	pageNumber: zod.int(),
	totalPages: zod.int(),
	totalCount: zod.int(),
	hasPreviousPage: zod.boolean(),
	hasNextPage: zod.boolean(),
});

export const BookingGetPathParams = zod.object({
	id: zod.int(),
});

export const BookingGetPathResponse = zod.object({
	bookingId: zod.int(),
	outletId: zod.int(),
	outletSlug: zod.string(),
	outletName: zod.string(),
	facilityId: zod.int(),
	facilityName: zod.string(),
	slotId: zod.string(),
	slotStartDatetime: zod.iso.datetime({ offset: true }),
});

export const BookingCreateBody = zod.object({
	bookings: zod.array(
		zod.object({
			slotId: zod.string(),
			slotContractId: zod.int(),
			name: zod.string().nullish(),
			email: zod.string().nullish(),
			cellphone: zod.string().nullish(),
		})
	),
	extras: zod.array(
		zod.object({
			extraId: zod.int(),
			amount: zod.int(),
		})
	),
});

export const BookingCreateResponse = zod.object({
	id: zod.int(),
});
