/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ExampleResponse = zod.string();

export const ExampleVerifyQueryParams = zod.object({
	code: zod.string(),
});

export const ExampleVerifyResponse = zod.boolean();
