/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ExtraGetFacilityParams = zod.object({
	facilityId: zod.int(),
});

export const ExtraGetFacilityResponseItem = zod.object({
	id: zod.int(),
	facilityId: zod.int(),
	facility: zod.object({
		created: zod.iso.datetime({ offset: true }),
		createdBy: zod.string().nullish(),
		lastModified: zod.iso.datetime({ offset: true }).nullish(),
		lastModifiedBy: zod.string().nullish(),
		id: zod.int(),
		name: zod.string(),
		outletId: zod.int(),
		outlet: zod.object({
			created: zod.iso.datetime({ offset: true }),
			createdBy: zod.string().nullish(),
			lastModified: zod.iso.datetime({ offset: true }).nullish(),
			lastModifiedBy: zod.string().nullish(),
			id: zod.int(),
			slug: zod.string(),
			name: zod.string(),
			businessId: zod.int(),
			business: zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.int(),
				name: zod.string(),
				outlets: zod.array(zod.unknown()),
			}),
			vatNumber: zod.string(),
			logo: zod.string().nullish(),
			address: zod.string().nullish(),
			description: zod.string().nullish(),
			registration: zod.string().nullish(),
			tags: zod.string().nullish(),
			contact: zod.string().nullish(),
			email: zod.string().nullish(),
			operatingHours: zod.string().nullish(),
			displayName: zod.string(),
			outletTypeId: zod.int(),
			outletType: zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.int(),
				name: zod.string(),
			}),
			isActive: zod.boolean(),
			facilities: zod.array(zod.unknown()),
			extras: zod.array(zod.unknown()),
		}),
		isActive: zod.boolean().nullish(),
		facilityTypeId: zod.int(),
		contact: zod.string().nullish(),
		email: zod.string().nullish(),
		rules: zod.string().nullish(),
		operatingHours: zod.string().nullish(),
		facilityType: zod.object({
			id: zod.int(),
			name: zod.string(),
		}),
		resources: zod.array(
			zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.int(),
				name: zod.string(),
				facilityId: zod.int(),
				facility: zod.unknown(),
				isActive: zod.boolean(),
				slots: zod.array(
					zod.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.string(),
						resourceId: zod.int().nullish(),
						resource: zod.unknown().nullish(),
						facilityId: zod.int().nullish(),
						facility: zod.unknown().nullish(),
						startDatetime: zod.iso.datetime({ offset: true }),
						endDatetime: zod.iso.datetime({ offset: true }).nullish(),
						maxBookings: zod.int(),
						slotContracts: zod.array(
							zod.object({
								created: zod.iso.datetime({ offset: true }),
								createdBy: zod.string().nullish(),
								lastModified: zod.iso.datetime({ offset: true }).nullish(),
								lastModifiedBy: zod.string().nullish(),
								id: zod.int(),
								slotId: zod.string(),
								slot: zod.unknown(),
								contractId: zod.int(),
								contract: zod.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.int(),
									name: zod.string(),
									price: zod.number(),
									frequency: zod.int(),
									startDate: zod.iso.datetime({ offset: true }),
									endDate: zod.iso.datetime({ offset: true }),
									isActive: zod.boolean(),
									isPublic: zod.boolean(),
									contractFacilities: zod.array(
										zod.object({
											contractId: zod.int(),
											contract: zod.unknown(),
											facilityId: zod.int(),
											facility: zod.unknown(),
										})
									),
								}),
								price: zod.number(),
								validationId: zod.int().nullish(),
								validation: zod
									.object({
										id: zod.int(),
										name: zod.string(),
									})
									.nullish(),
								canPayLater: zod.boolean(),
								description: zod.string().nullish(),
							})
						),
						extraBookings: zod.array(
							zod.object({
								extraId: zod.int(),
								extra: zod.unknown(),
								bookingId: zod.int(),
								booking: zod.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.int(),
									bookingStatusId: zod.int(),
									bookingStatus: zod.object({
										id: zod.int(),
										name: zod.string(),
									}),
									bookingStatusDate: zod.iso.datetime({ offset: true }),
									userId: zod.string().nullish(),
									user: zod
										.object({
											id: zod.string(),
											userName: zod.string().nullish(),
											normalizedUserName: zod.string().nullish(),
											email: zod.string().nullish(),
											normalizedEmail: zod.string().nullish(),
											emailConfirmed: zod.boolean(),
											passwordHash: zod.string().nullish(),
											securityStamp: zod.string().nullish(),
											concurrencyStamp: zod.string().nullish(),
											phoneNumber: zod.string().nullish(),
											phoneNumberConfirmed: zod.boolean(),
											twoFactorEnabled: zod.boolean(),
											lockoutEnd: zod.iso.datetime({ offset: true }).nullish(),
											lockoutEnabled: zod.boolean(),
											accessFailedCount: zod.int(),
											firstName: zod.string(),
											lastName: zod.string(),
											picture: zod.string().nullish(),
											userContracts: zod.array(
												zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													contractId: zod.int(),
													contract: zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														name: zod.string(),
														price: zod.number(),
														frequency: zod.int(),
														startDate: zod.iso.datetime({ offset: true }),
														endDate: zod.iso.datetime({ offset: true }),
														isActive: zod.boolean(),
														isPublic: zod.boolean(),
														contractFacilities: zod.array(
															zod.object({
																contractId: zod.int(),
																contract: zod.unknown(),
																facilityId: zod.int(),
																facility: zod.unknown(),
															})
														),
													}),
													startDate: zod.iso.datetime({ offset: true }),
													endDate: zod.iso.datetime({ offset: true }).nullish(),
													price: zod.number(),
													isActive: zod.boolean(),
													userId: zod.string(),
													user: zod.unknown(),
													voucherGrants: zod.array(
														zod.object({
															id: zod.string(),
															walletId: zod.string(),
															wallet: zod.object({
																id: zod.string(),
																userId: zod.string(),
																user: zod.unknown(),
																isActive: zod.boolean(),
																currency: zod.string(),
																balance: zod
																	.object({
																		walletId: zod.string(),
																		wallet: zod.unknown(),
																		balance: zod.number(),
																		updatedAt: zod.iso.datetime({ offset: true }),
																	})
																	.nullish(),
																transactions: zod.array(
																	zod.object({
																		id: zod.string(),
																		walletId: zod.string(),
																		wallet: zod.unknown(),
																		amount: zod.number(),
																		walletTransactionStatusId: zod.int(),
																		walletTransactionStatus: zod.object({
																			id: zod.int(),
																			name: zod.string(),
																		}),
																		walletTransactionTypeId: zod.int(),
																		walletTransactionType: zod.object({
																			id: zod.int(),
																			name: zod.string(),
																		}),
																		createdAt: zod.iso.datetime({ offset: true }),
																		referenceId: zod.string(),
																	})
																),
																voucherGrants: zod.array(zod.unknown()),
															}),
															userContractId: zod.int(),
															userContract: zod.unknown(),
															voucherId: zod.int(),
															voucher: zod.object({
																id: zod.int(),
																name: zod.string(),
																description: zod.string(),
																isExtra: zod.boolean(),
																redemptionKind: zod.enum({
																	Entitlement: 1,
																	Credit: 2,
																	Discount: 3,
																}),
																discountMode: zod
																	.enum({
																		Percentage: 1,
																		FixedAmount: 2,
																	})
																	.nullish(),
																discountValue: zod.number().nullish(),
																maxDiscountAmount: zod.number().nullish(),
															}),
															amountGranted: zod.number(),
															amountRemaining: zod.number(),
															grantedAt: zod.iso.datetime({ offset: true }),
															expiryDate: zod.iso.datetime({ offset: true }),
														})
													),
												})
											),
											userRoles: zod.array(
												zod.object({
													userId: zod.string(),
													roleId: zod.string(),
													id: zod.int(),
													facilityId: zod.int().nullish(),
													facility: zod.unknown().nullish(),
													role: zod.object({
														id: zod.string(),
														name: zod.string().nullish(),
														normalizedName: zod.string().nullish(),
														concurrencyStamp: zod.string().nullish(),
													}),
												})
											),
											wallet: zod
												.object({
													id: zod.string(),
													userId: zod.string(),
													user: zod.unknown(),
													isActive: zod.boolean(),
													currency: zod.string(),
													balance: zod
														.object({
															walletId: zod.string(),
															wallet: zod.unknown(),
															balance: zod.number(),
															updatedAt: zod.iso.datetime({ offset: true }),
														})
														.nullish(),
													transactions: zod.array(
														zod.object({
															id: zod.string(),
															walletId: zod.string(),
															wallet: zod.unknown(),
															amount: zod.number(),
															walletTransactionStatusId: zod.int(),
															walletTransactionStatus: zod.object({
																id: zod.int(),
																name: zod.string(),
															}),
															walletTransactionTypeId: zod.int(),
															walletTransactionType: zod.object({
																id: zod.int(),
																name: zod.string(),
															}),
															createdAt: zod.iso.datetime({ offset: true }),
															referenceId: zod.string(),
														})
													),
													voucherGrants: zod.array(
														zod.object({
															id: zod.string(),
															walletId: zod.string(),
															wallet: zod.unknown(),
															userContractId: zod.int(),
															userContract: zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																contractId: zod.int(),
																contract: zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	name: zod.string(),
																	price: zod.number(),
																	frequency: zod.int(),
																	startDate: zod.iso.datetime({ offset: true }),
																	endDate: zod.iso.datetime({ offset: true }),
																	isActive: zod.boolean(),
																	isPublic: zod.boolean(),
																	contractFacilities: zod.array(
																		zod.object({
																			contractId: zod.int(),
																			contract: zod.unknown(),
																			facilityId: zod.int(),
																			facility: zod.unknown(),
																		})
																	),
																}),
																startDate: zod.iso.datetime({ offset: true }),
																endDate: zod.iso.datetime({ offset: true }).nullish(),
																price: zod.number(),
																isActive: zod.boolean(),
																userId: zod.string(),
																user: zod.unknown(),
																voucherGrants: zod.array(zod.unknown()),
															}),
															voucherId: zod.int(),
															voucher: zod.object({
																id: zod.int(),
																name: zod.string(),
																description: zod.string(),
																isExtra: zod.boolean(),
																redemptionKind: zod.enum({
																	Entitlement: 1,
																	Credit: 2,
																	Discount: 3,
																}),
																discountMode: zod
																	.enum({
																		Percentage: 1,
																		FixedAmount: 2,
																	})
																	.nullish(),
																discountValue: zod.number().nullish(),
																maxDiscountAmount: zod.number().nullish(),
															}),
															amountGranted: zod.number(),
															amountRemaining: zod.number(),
															grantedAt: zod.iso.datetime({ offset: true }),
															expiryDate: zod.iso.datetime({ offset: true }),
														})
													),
												})
												.nullish(),
											lastSync: zod.iso.datetime({ offset: true }),
										})
										.nullish(),
									isPaid: zod.boolean(),
									amountOutstanding: zod.number(),
									amountPaid: zod.number(),
									expiresAt: zod.iso.datetime({ offset: true }),
									slotContractBookings: zod.array(
										zod.object({
											id: zod.int(),
											slotContractId: zod.int(),
											slotContract: zod.object({
												created: zod.iso.datetime({ offset: true }),
												createdBy: zod.string().nullish(),
												lastModified: zod.iso.datetime({ offset: true }).nullish(),
												lastModifiedBy: zod.string().nullish(),
												id: zod.int(),
												slotId: zod.string(),
												slot: zod.unknown(),
												contractId: zod.int(),
												contract: zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													name: zod.string(),
													price: zod.number(),
													frequency: zod.int(),
													startDate: zod.iso.datetime({ offset: true }),
													endDate: zod.iso.datetime({ offset: true }),
													isActive: zod.boolean(),
													isPublic: zod.boolean(),
													contractFacilities: zod.array(
														zod.object({
															contractId: zod.int(),
															contract: zod.unknown(),
															facilityId: zod.int(),
															facility: zod.unknown(),
														})
													),
												}),
												price: zod.number(),
												validationId: zod.int().nullish(),
												validation: zod
													.object({
														id: zod.int(),
														name: zod.string(),
													})
													.nullish(),
												canPayLater: zod.boolean(),
												description: zod.string().nullish(),
											}),
											bookingId: zod.int(),
											booking: zod.unknown(),
											userId: zod.string().nullish(),
											name: zod.string().nullish(),
											email: zod.string().nullish(),
											cellphone: zod.string().nullish(),
										})
									),
									extraBookings: zod.array(zod.unknown()),
								}),
								amount: zod.int(),
							})
						),
					})
				),
			})
		),
		slots: zod.array(
			zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.string(),
				resourceId: zod.int().nullish(),
				resource: zod
					.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.int(),
						name: zod.string(),
						facilityId: zod.int(),
						facility: zod.unknown(),
						isActive: zod.boolean(),
						slots: zod.array(zod.unknown()),
					})
					.nullish(),
				facilityId: zod.int().nullish(),
				facility: zod.unknown().nullish(),
				startDatetime: zod.iso.datetime({ offset: true }),
				endDatetime: zod.iso.datetime({ offset: true }).nullish(),
				maxBookings: zod.int(),
				slotContracts: zod.array(
					zod.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.int(),
						slotId: zod.string(),
						slot: zod.unknown(),
						contractId: zod.int(),
						contract: zod.object({
							created: zod.iso.datetime({ offset: true }),
							createdBy: zod.string().nullish(),
							lastModified: zod.iso.datetime({ offset: true }).nullish(),
							lastModifiedBy: zod.string().nullish(),
							id: zod.int(),
							name: zod.string(),
							price: zod.number(),
							frequency: zod.int(),
							startDate: zod.iso.datetime({ offset: true }),
							endDate: zod.iso.datetime({ offset: true }),
							isActive: zod.boolean(),
							isPublic: zod.boolean(),
							contractFacilities: zod.array(
								zod.object({
									contractId: zod.int(),
									contract: zod.unknown(),
									facilityId: zod.int(),
									facility: zod.unknown(),
								})
							),
						}),
						price: zod.number(),
						validationId: zod.int().nullish(),
						validation: zod
							.object({
								id: zod.int(),
								name: zod.string(),
							})
							.nullish(),
						canPayLater: zod.boolean(),
						description: zod.string().nullish(),
					})
				),
				extraBookings: zod.array(
					zod.object({
						extraId: zod.int(),
						extra: zod.unknown(),
						bookingId: zod.int(),
						booking: zod.object({
							created: zod.iso.datetime({ offset: true }),
							createdBy: zod.string().nullish(),
							lastModified: zod.iso.datetime({ offset: true }).nullish(),
							lastModifiedBy: zod.string().nullish(),
							id: zod.int(),
							bookingStatusId: zod.int(),
							bookingStatus: zod.object({
								id: zod.int(),
								name: zod.string(),
							}),
							bookingStatusDate: zod.iso.datetime({ offset: true }),
							userId: zod.string().nullish(),
							user: zod
								.object({
									id: zod.string(),
									userName: zod.string().nullish(),
									normalizedUserName: zod.string().nullish(),
									email: zod.string().nullish(),
									normalizedEmail: zod.string().nullish(),
									emailConfirmed: zod.boolean(),
									passwordHash: zod.string().nullish(),
									securityStamp: zod.string().nullish(),
									concurrencyStamp: zod.string().nullish(),
									phoneNumber: zod.string().nullish(),
									phoneNumberConfirmed: zod.boolean(),
									twoFactorEnabled: zod.boolean(),
									lockoutEnd: zod.iso.datetime({ offset: true }).nullish(),
									lockoutEnabled: zod.boolean(),
									accessFailedCount: zod.int(),
									firstName: zod.string(),
									lastName: zod.string(),
									picture: zod.string().nullish(),
									userContracts: zod.array(
										zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											contractId: zod.int(),
											contract: zod.object({
												created: zod.iso.datetime({ offset: true }),
												createdBy: zod.string().nullish(),
												lastModified: zod.iso.datetime({ offset: true }).nullish(),
												lastModifiedBy: zod.string().nullish(),
												id: zod.int(),
												name: zod.string(),
												price: zod.number(),
												frequency: zod.int(),
												startDate: zod.iso.datetime({ offset: true }),
												endDate: zod.iso.datetime({ offset: true }),
												isActive: zod.boolean(),
												isPublic: zod.boolean(),
												contractFacilities: zod.array(
													zod.object({
														contractId: zod.int(),
														contract: zod.unknown(),
														facilityId: zod.int(),
														facility: zod.unknown(),
													})
												),
											}),
											startDate: zod.iso.datetime({ offset: true }),
											endDate: zod.iso.datetime({ offset: true }).nullish(),
											price: zod.number(),
											isActive: zod.boolean(),
											userId: zod.string(),
											user: zod.unknown(),
											voucherGrants: zod.array(
												zod.object({
													id: zod.string(),
													walletId: zod.string(),
													wallet: zod.object({
														id: zod.string(),
														userId: zod.string(),
														user: zod.unknown(),
														isActive: zod.boolean(),
														currency: zod.string(),
														balance: zod
															.object({
																walletId: zod.string(),
																wallet: zod.unknown(),
																balance: zod.number(),
																updatedAt: zod.iso.datetime({ offset: true }),
															})
															.nullish(),
														transactions: zod.array(
															zod.object({
																id: zod.string(),
																walletId: zod.string(),
																wallet: zod.unknown(),
																amount: zod.number(),
																walletTransactionStatusId: zod.int(),
																walletTransactionStatus: zod.object({
																	id: zod.int(),
																	name: zod.string(),
																}),
																walletTransactionTypeId: zod.int(),
																walletTransactionType: zod.object({
																	id: zod.int(),
																	name: zod.string(),
																}),
																createdAt: zod.iso.datetime({ offset: true }),
																referenceId: zod.string(),
															})
														),
														voucherGrants: zod.array(zod.unknown()),
													}),
													userContractId: zod.int(),
													userContract: zod.unknown(),
													voucherId: zod.int(),
													voucher: zod.object({
														id: zod.int(),
														name: zod.string(),
														description: zod.string(),
														isExtra: zod.boolean(),
														redemptionKind: zod.enum({
															Entitlement: 1,
															Credit: 2,
															Discount: 3,
														}),
														discountMode: zod
															.enum({
																Percentage: 1,
																FixedAmount: 2,
															})
															.nullish(),
														discountValue: zod.number().nullish(),
														maxDiscountAmount: zod.number().nullish(),
													}),
													amountGranted: zod.number(),
													amountRemaining: zod.number(),
													grantedAt: zod.iso.datetime({ offset: true }),
													expiryDate: zod.iso.datetime({ offset: true }),
												})
											),
										})
									),
									userRoles: zod.array(
										zod.object({
											userId: zod.string(),
											roleId: zod.string(),
											id: zod.int(),
											facilityId: zod.int().nullish(),
											facility: zod.unknown().nullish(),
											role: zod.object({
												id: zod.string(),
												name: zod.string().nullish(),
												normalizedName: zod.string().nullish(),
												concurrencyStamp: zod.string().nullish(),
											}),
										})
									),
									wallet: zod
										.object({
											id: zod.string(),
											userId: zod.string(),
											user: zod.unknown(),
											isActive: zod.boolean(),
											currency: zod.string(),
											balance: zod
												.object({
													walletId: zod.string(),
													wallet: zod.unknown(),
													balance: zod.number(),
													updatedAt: zod.iso.datetime({ offset: true }),
												})
												.nullish(),
											transactions: zod.array(
												zod.object({
													id: zod.string(),
													walletId: zod.string(),
													wallet: zod.unknown(),
													amount: zod.number(),
													walletTransactionStatusId: zod.int(),
													walletTransactionStatus: zod.object({
														id: zod.int(),
														name: zod.string(),
													}),
													walletTransactionTypeId: zod.int(),
													walletTransactionType: zod.object({
														id: zod.int(),
														name: zod.string(),
													}),
													createdAt: zod.iso.datetime({ offset: true }),
													referenceId: zod.string(),
												})
											),
											voucherGrants: zod.array(
												zod.object({
													id: zod.string(),
													walletId: zod.string(),
													wallet: zod.unknown(),
													userContractId: zod.int(),
													userContract: zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														contractId: zod.int(),
														contract: zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															name: zod.string(),
															price: zod.number(),
															frequency: zod.int(),
															startDate: zod.iso.datetime({ offset: true }),
															endDate: zod.iso.datetime({ offset: true }),
															isActive: zod.boolean(),
															isPublic: zod.boolean(),
															contractFacilities: zod.array(
																zod.object({
																	contractId: zod.int(),
																	contract: zod.unknown(),
																	facilityId: zod.int(),
																	facility: zod.unknown(),
																})
															),
														}),
														startDate: zod.iso.datetime({ offset: true }),
														endDate: zod.iso.datetime({ offset: true }).nullish(),
														price: zod.number(),
														isActive: zod.boolean(),
														userId: zod.string(),
														user: zod.unknown(),
														voucherGrants: zod.array(zod.unknown()),
													}),
													voucherId: zod.int(),
													voucher: zod.object({
														id: zod.int(),
														name: zod.string(),
														description: zod.string(),
														isExtra: zod.boolean(),
														redemptionKind: zod.enum({
															Entitlement: 1,
															Credit: 2,
															Discount: 3,
														}),
														discountMode: zod
															.enum({
																Percentage: 1,
																FixedAmount: 2,
															})
															.nullish(),
														discountValue: zod.number().nullish(),
														maxDiscountAmount: zod.number().nullish(),
													}),
													amountGranted: zod.number(),
													amountRemaining: zod.number(),
													grantedAt: zod.iso.datetime({ offset: true }),
													expiryDate: zod.iso.datetime({ offset: true }),
												})
											),
										})
										.nullish(),
									lastSync: zod.iso.datetime({ offset: true }),
								})
								.nullish(),
							isPaid: zod.boolean(),
							amountOutstanding: zod.number(),
							amountPaid: zod.number(),
							expiresAt: zod.iso.datetime({ offset: true }),
							slotContractBookings: zod.array(
								zod.object({
									id: zod.int(),
									slotContractId: zod.int(),
									slotContract: zod.object({
										created: zod.iso.datetime({ offset: true }),
										createdBy: zod.string().nullish(),
										lastModified: zod.iso.datetime({ offset: true }).nullish(),
										lastModifiedBy: zod.string().nullish(),
										id: zod.int(),
										slotId: zod.string(),
										slot: zod.unknown(),
										contractId: zod.int(),
										contract: zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											name: zod.string(),
											price: zod.number(),
											frequency: zod.int(),
											startDate: zod.iso.datetime({ offset: true }),
											endDate: zod.iso.datetime({ offset: true }),
											isActive: zod.boolean(),
											isPublic: zod.boolean(),
											contractFacilities: zod.array(
												zod.object({
													contractId: zod.int(),
													contract: zod.unknown(),
													facilityId: zod.int(),
													facility: zod.unknown(),
												})
											),
										}),
										price: zod.number(),
										validationId: zod.int().nullish(),
										validation: zod
											.object({
												id: zod.int(),
												name: zod.string(),
											})
											.nullish(),
										canPayLater: zod.boolean(),
										description: zod.string().nullish(),
									}),
									bookingId: zod.int(),
									booking: zod.unknown(),
									userId: zod.string().nullish(),
									name: zod.string().nullish(),
									email: zod.string().nullish(),
									cellphone: zod.string().nullish(),
								})
							),
							extraBookings: zod.array(zod.unknown()),
						}),
						amount: zod.int(),
					})
				),
			})
		),
		paymentProviderConfigs: zod.array(
			zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.int(),
				facilityId: zod.int(),
				facility: zod.unknown(),
				providerKey: zod.string(),
				type: zod.enum({
					/** PeachPayments */
					Peach: 0,
					/** Payfast */
					Payfast: 1,
				}),
				iv: zod.string(),
				encryptedSettings: zod.string(),
				enabled: zod.boolean(),
			})
		),
		contractFacilities: zod.array(
			zod.object({
				contractId: zod.int(),
				contract: zod.object({
					created: zod.iso.datetime({ offset: true }),
					createdBy: zod.string().nullish(),
					lastModified: zod.iso.datetime({ offset: true }).nullish(),
					lastModifiedBy: zod.string().nullish(),
					id: zod.int(),
					name: zod.string(),
					price: zod.number(),
					frequency: zod.int(),
					startDate: zod.iso.datetime({ offset: true }),
					endDate: zod.iso.datetime({ offset: true }),
					isActive: zod.boolean(),
					isPublic: zod.boolean(),
					contractFacilities: zod.array(zod.unknown()),
				}),
				facilityId: zod.int(),
				facility: zod.unknown(),
			})
		),
	}),
	outletId: zod.int(),
	name: zod.string(),
	code: zod.string(),
	price: zod.number(),
	isAvailable: zod.boolean(),
	isOnline: zod.boolean(),
});
export const ExtraGetFacilityResponse = zod.array(ExtraGetFacilityResponseItem);
