/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const FacilityPaymentMethodsParams = zod.object({
	facilityId: zod.int(),
});

export const FacilityPaymentMethodsResponseItem = zod.object({
	providerName: zod.string(),
	type: zod.string(),
});
export const FacilityPaymentMethodsResponse = zod.array(FacilityPaymentMethodsResponseItem);

export const FacilityGetParams = zod.object({
	id: zod.int(),
});

export const FacilityGetResponse = zod.object({
	id: zod.int(),
	name: zod.string(),
	outletId: zod.int(),
	isActive: zod.boolean().nullish(),
	facilityTypeId: zod.int(),
	facilityType: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	contact: zod.string().nullish(),
	email: zod.string().nullish(),
	rules: zod.string().nullish(),
	operatingHours: zod.string().nullish(),
});
