/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const OutletGetBasicParams = zod.object({
	slug: zod.string(),
});

export const OutletGetBasicResponse = zod.object({
	id: zod.int(),
	slug: zod.string(),
	name: zod.string(),
	businessName: zod.string(),
	logo: zod.string().nullish(),
	displayName: zod.string(),
	outletTypeId: zod.int(),
	outletType: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	isActive: zod.boolean(),
	facilities: zod.array(
		zod.object({
			id: zod.int(),
			name: zod.string(),
			isActive: zod.boolean().nullish(),
			facilityTypeId: zod.int(),
			facilityTypeName: zod.string(),
		})
	),
});

export const OutletGetAllQueryParams = zod.object({
	search: zod.string().nullish(),
	sorts: zod.string().nullish(),
	filters: zod.string().nullish(),
	page: zod.int().nullish(),
	pageSize: zod.int().nullish(),
});

export const OutletGetAllResponse = zod.object({
	items: zod.array(
		zod.object({
			created: zod.iso.datetime({ offset: true }),
			createdBy: zod.string().nullish(),
			lastModified: zod.iso.datetime({ offset: true }).nullish(),
			lastModifiedBy: zod.string().nullish(),
			id: zod.int(),
			slug: zod.string(),
			name: zod.string(),
			businessId: zod.int(),
			business: zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.int(),
				name: zod.string(),
				outlets: zod.array(zod.unknown()),
				contracts: zod.array(
					zod.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.int(),
						name: zod.string(),
						businessId: zod.int(),
						business: zod.unknown(),
					})
				),
				contractFields: zod.array(
					zod.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.int(),
						name: zod.string(),
						fieldValidation: zod.string().nullish(),
						businessId: zod.int(),
						business: zod.unknown(),
						contractFieldConfigs: zod.array(
							zod.object({
								created: zod.iso.datetime({ offset: true }),
								createdBy: zod.string().nullish(),
								lastModified: zod.iso.datetime({ offset: true }).nullish(),
								lastModifiedBy: zod.string().nullish(),
								id: zod.int(),
								contractId: zod.int(),
								contract: zod.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.int(),
									name: zod.string(),
									businessId: zod.int(),
									business: zod.unknown(),
								}),
								contractConfigId: zod.int(),
								contractField: zod.unknown(),
								isActive: zod.boolean(),
							})
						),
					})
				),
			}),
			vatNumber: zod.string(),
			logo: zod.string().nullish(),
			address: zod.string().nullish(),
			description: zod.string().nullish(),
			registration: zod.string().nullish(),
			tags: zod.string().nullish(),
			contact: zod.string().nullish(),
			email: zod.string().nullish(),
			operatingHours: zod.string().nullish(),
			displayName: zod.string(),
			outletTypeId: zod.int(),
			outletType: zod.object({
				created: zod.iso.datetime({ offset: true }),
				createdBy: zod.string().nullish(),
				lastModified: zod.iso.datetime({ offset: true }).nullish(),
				lastModifiedBy: zod.string().nullish(),
				id: zod.int(),
				name: zod.string(),
			}),
			isActive: zod.boolean(),
			facilities: zod.array(
				zod.object({
					created: zod.iso.datetime({ offset: true }),
					createdBy: zod.string().nullish(),
					lastModified: zod.iso.datetime({ offset: true }).nullish(),
					lastModifiedBy: zod.string().nullish(),
					id: zod.int(),
					name: zod.string(),
					outletId: zod.int(),
					outlet: zod.unknown(),
					isActive: zod.boolean().nullish(),
					facilityTypeId: zod.int(),
					contact: zod.string().nullish(),
					email: zod.string().nullish(),
					rules: zod.string().nullish(),
					operatingHours: zod.string().nullish(),
					facilityType: zod.object({
						id: zod.int(),
						name: zod.string(),
					}),
					resources: zod.array(
						zod.object({
							created: zod.iso.datetime({ offset: true }),
							createdBy: zod.string().nullish(),
							lastModified: zod.iso.datetime({ offset: true }).nullish(),
							lastModifiedBy: zod.string().nullish(),
							id: zod.int(),
							name: zod.string(),
							facilityId: zod.int(),
							facility: zod.unknown(),
							isActive: zod.boolean(),
							slots: zod.array(
								zod.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.string(),
									resourceId: zod.int().nullish(),
									resource: zod.unknown().nullish(),
									facilityId: zod.int().nullish(),
									facility: zod.unknown().nullish(),
									startDatetime: zod.iso.datetime({ offset: true }),
									endDatetime: zod.iso.datetime({ offset: true }).nullish(),
									maxBookings: zod.int(),
									slotContracts: zod.array(
										zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											slotId: zod.string(),
											slot: zod.unknown(),
											contractId: zod.int(),
											contract: zod.object({
												created: zod.iso.datetime({ offset: true }),
												createdBy: zod.string().nullish(),
												lastModified: zod.iso.datetime({ offset: true }).nullish(),
												lastModifiedBy: zod.string().nullish(),
												id: zod.int(),
												name: zod.string(),
												businessId: zod.int(),
												business: zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													name: zod.string(),
													outlets: zod.array(zod.unknown()),
													contracts: zod.array(zod.unknown()),
													contractFields: zod.array(
														zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															name: zod.string(),
															fieldValidation: zod.string().nullish(),
															businessId: zod.int(),
															business: zod.unknown(),
															contractFieldConfigs: zod.array(
																zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	contractId: zod.int(),
																	contract: zod.unknown(),
																	contractConfigId: zod.int(),
																	contractField: zod.unknown(),
																	isActive: zod.boolean(),
																})
															),
														})
													),
												}),
											}),
											price: zod.number(),
											validationId: zod.int().nullish(),
											validation: zod
												.object({
													id: zod.int(),
													name: zod.string(),
												})
												.nullish(),
											canPayLater: zod.boolean(),
											description: zod.string().nullish(),
										})
									),
									extraBookings: zod.array(
										zod.object({
											extraId: zod.int(),
											extra: zod.object({
												id: zod.int(),
												facilityId: zod.int(),
												facility: zod.unknown(),
												outletId: zod.int(),
												name: zod.string(),
												code: zod.string(),
												price: zod.number(),
												isAvailable: zod.boolean(),
												isOnline: zod.boolean(),
											}),
											bookingId: zod.int(),
											booking: zod.object({
												created: zod.iso.datetime({ offset: true }),
												createdBy: zod.string().nullish(),
												lastModified: zod.iso.datetime({ offset: true }).nullish(),
												lastModifiedBy: zod.string().nullish(),
												id: zod.int(),
												bookingStatusId: zod.int(),
												bookingStatus: zod.object({
													id: zod.int(),
													name: zod.string(),
												}),
												bookingStatusDate: zod.iso.datetime({ offset: true }),
												userId: zod.string().nullish(),
												user: zod
													.object({
														id: zod.string(),
														userName: zod.string().nullish(),
														normalizedUserName: zod.string().nullish(),
														email: zod.string().nullish(),
														normalizedEmail: zod.string().nullish(),
														emailConfirmed: zod.boolean(),
														passwordHash: zod.string().nullish(),
														securityStamp: zod.string().nullish(),
														concurrencyStamp: zod.string().nullish(),
														phoneNumber: zod.string().nullish(),
														phoneNumberConfirmed: zod.boolean(),
														twoFactorEnabled: zod.boolean(),
														lockoutEnd: zod.iso.datetime({ offset: true }).nullish(),
														lockoutEnabled: zod.boolean(),
														accessFailedCount: zod.int(),
														firstName: zod.string(),
														lastName: zod.string(),
														picture: zod.string().nullish(),
														userContracts: zod.array(
															zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																contractId: zod.int(),
																contract: zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	name: zod.string(),
																	businessId: zod.int(),
																	business: zod.object({
																		created: zod.iso.datetime({ offset: true }),
																		createdBy: zod.string().nullish(),
																		lastModified: zod.iso.datetime({ offset: true }).nullish(),
																		lastModifiedBy: zod.string().nullish(),
																		id: zod.int(),
																		name: zod.string(),
																		outlets: zod.array(zod.unknown()),
																		contracts: zod.array(zod.unknown()),
																		contractFields: zod.array(
																			zod.object({
																				created: zod.iso.datetime({ offset: true }),
																				createdBy: zod.string().nullish(),
																				lastModified: zod.iso.datetime({ offset: true }).nullish(),
																				lastModifiedBy: zod.string().nullish(),
																				id: zod.int(),
																				name: zod.string(),
																				fieldValidation: zod.string().nullish(),
																				businessId: zod.int(),
																				business: zod.unknown(),
																				contractFieldConfigs: zod.array(
																					zod.object({
																						created: zod.iso.datetime({ offset: true }),
																						createdBy: zod.string().nullish(),
																						lastModified: zod.iso.datetime({ offset: true }).nullish(),
																						lastModifiedBy: zod.string().nullish(),
																						id: zod.int(),
																						contractId: zod.int(),
																						contract: zod.unknown(),
																						contractConfigId: zod.int(),
																						contractField: zod.unknown(),
																						isActive: zod.boolean(),
																					})
																				),
																			})
																		),
																	}),
																}),
																startDate: zod.iso.datetime({ offset: true }),
																endDate: zod.iso.datetime({ offset: true }).nullish(),
																price: zod.number(),
																isActive: zod.boolean(),
																userId: zod.string(),
																user: zod.unknown(),
															})
														),
														userRoles: zod.array(
															zod.object({
																userId: zod.string(),
																roleId: zod.string(),
																id: zod.int(),
																facilityId: zod.int().nullish(),
																facility: zod.unknown().nullish(),
																role: zod.object({
																	id: zod.string(),
																	name: zod.string().nullish(),
																	normalizedName: zod.string().nullish(),
																	concurrencyStamp: zod.string().nullish(),
																}),
															})
														),
														lastSync: zod.iso.datetime({ offset: true }),
													})
													.nullish(),
												isPaid: zod.boolean(),
												amountOutstanding: zod.number(),
												amountPaid: zod.number(),
												expiresAt: zod.iso.datetime({ offset: true }),
												slotContractBookings: zod.array(
													zod.object({
														id: zod.int(),
														slotContractId: zod.int(),
														slotContract: zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															slotId: zod.string(),
															slot: zod.unknown(),
															contractId: zod.int(),
															contract: zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																name: zod.string(),
																businessId: zod.int(),
																business: zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	name: zod.string(),
																	outlets: zod.array(zod.unknown()),
																	contracts: zod.array(zod.unknown()),
																	contractFields: zod.array(
																		zod.object({
																			created: zod.iso.datetime({ offset: true }),
																			createdBy: zod.string().nullish(),
																			lastModified: zod.iso.datetime({ offset: true }).nullish(),
																			lastModifiedBy: zod.string().nullish(),
																			id: zod.int(),
																			name: zod.string(),
																			fieldValidation: zod.string().nullish(),
																			businessId: zod.int(),
																			business: zod.unknown(),
																			contractFieldConfigs: zod.array(
																				zod.object({
																					created: zod.iso.datetime({ offset: true }),
																					createdBy: zod.string().nullish(),
																					lastModified: zod.iso.datetime({ offset: true }).nullish(),
																					lastModifiedBy: zod.string().nullish(),
																					id: zod.int(),
																					contractId: zod.int(),
																					contract: zod.unknown(),
																					contractConfigId: zod.int(),
																					contractField: zod.unknown(),
																					isActive: zod.boolean(),
																				})
																			),
																		})
																	),
																}),
															}),
															price: zod.number(),
															validationId: zod.int().nullish(),
															validation: zod
																.object({
																	id: zod.int(),
																	name: zod.string(),
																})
																.nullish(),
															canPayLater: zod.boolean(),
															description: zod.string().nullish(),
														}),
														bookingId: zod.int(),
														booking: zod.unknown(),
														userId: zod.string().nullish(),
														name: zod.string().nullish(),
														email: zod.string().nullish(),
														cellphone: zod.string().nullish(),
													})
												),
												extraBookings: zod.array(zod.unknown()),
											}),
											amount: zod.int(),
										})
									),
								})
							),
						})
					),
					slots: zod.array(
						zod.object({
							created: zod.iso.datetime({ offset: true }),
							createdBy: zod.string().nullish(),
							lastModified: zod.iso.datetime({ offset: true }).nullish(),
							lastModifiedBy: zod.string().nullish(),
							id: zod.string(),
							resourceId: zod.int().nullish(),
							resource: zod
								.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.int(),
									name: zod.string(),
									facilityId: zod.int(),
									facility: zod.unknown(),
									isActive: zod.boolean(),
									slots: zod.array(zod.unknown()),
								})
								.nullish(),
							facilityId: zod.int().nullish(),
							facility: zod.unknown().nullish(),
							startDatetime: zod.iso.datetime({ offset: true }),
							endDatetime: zod.iso.datetime({ offset: true }).nullish(),
							maxBookings: zod.int(),
							slotContracts: zod.array(
								zod.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.int(),
									slotId: zod.string(),
									slot: zod.unknown(),
									contractId: zod.int(),
									contract: zod.object({
										created: zod.iso.datetime({ offset: true }),
										createdBy: zod.string().nullish(),
										lastModified: zod.iso.datetime({ offset: true }).nullish(),
										lastModifiedBy: zod.string().nullish(),
										id: zod.int(),
										name: zod.string(),
										businessId: zod.int(),
										business: zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											name: zod.string(),
											outlets: zod.array(zod.unknown()),
											contracts: zod.array(zod.unknown()),
											contractFields: zod.array(
												zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													name: zod.string(),
													fieldValidation: zod.string().nullish(),
													businessId: zod.int(),
													business: zod.unknown(),
													contractFieldConfigs: zod.array(
														zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															contractId: zod.int(),
															contract: zod.unknown(),
															contractConfigId: zod.int(),
															contractField: zod.unknown(),
															isActive: zod.boolean(),
														})
													),
												})
											),
										}),
									}),
									price: zod.number(),
									validationId: zod.int().nullish(),
									validation: zod
										.object({
											id: zod.int(),
											name: zod.string(),
										})
										.nullish(),
									canPayLater: zod.boolean(),
									description: zod.string().nullish(),
								})
							),
							extraBookings: zod.array(
								zod.object({
									extraId: zod.int(),
									extra: zod.object({
										id: zod.int(),
										facilityId: zod.int(),
										facility: zod.unknown(),
										outletId: zod.int(),
										name: zod.string(),
										code: zod.string(),
										price: zod.number(),
										isAvailable: zod.boolean(),
										isOnline: zod.boolean(),
									}),
									bookingId: zod.int(),
									booking: zod.object({
										created: zod.iso.datetime({ offset: true }),
										createdBy: zod.string().nullish(),
										lastModified: zod.iso.datetime({ offset: true }).nullish(),
										lastModifiedBy: zod.string().nullish(),
										id: zod.int(),
										bookingStatusId: zod.int(),
										bookingStatus: zod.object({
											id: zod.int(),
											name: zod.string(),
										}),
										bookingStatusDate: zod.iso.datetime({ offset: true }),
										userId: zod.string().nullish(),
										user: zod
											.object({
												id: zod.string(),
												userName: zod.string().nullish(),
												normalizedUserName: zod.string().nullish(),
												email: zod.string().nullish(),
												normalizedEmail: zod.string().nullish(),
												emailConfirmed: zod.boolean(),
												passwordHash: zod.string().nullish(),
												securityStamp: zod.string().nullish(),
												concurrencyStamp: zod.string().nullish(),
												phoneNumber: zod.string().nullish(),
												phoneNumberConfirmed: zod.boolean(),
												twoFactorEnabled: zod.boolean(),
												lockoutEnd: zod.iso.datetime({ offset: true }).nullish(),
												lockoutEnabled: zod.boolean(),
												accessFailedCount: zod.int(),
												firstName: zod.string(),
												lastName: zod.string(),
												picture: zod.string().nullish(),
												userContracts: zod.array(
													zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														contractId: zod.int(),
														contract: zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															name: zod.string(),
															businessId: zod.int(),
															business: zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																name: zod.string(),
																outlets: zod.array(zod.unknown()),
																contracts: zod.array(zod.unknown()),
																contractFields: zod.array(
																	zod.object({
																		created: zod.iso.datetime({ offset: true }),
																		createdBy: zod.string().nullish(),
																		lastModified: zod.iso.datetime({ offset: true }).nullish(),
																		lastModifiedBy: zod.string().nullish(),
																		id: zod.int(),
																		name: zod.string(),
																		fieldValidation: zod.string().nullish(),
																		businessId: zod.int(),
																		business: zod.unknown(),
																		contractFieldConfigs: zod.array(
																			zod.object({
																				created: zod.iso.datetime({ offset: true }),
																				createdBy: zod.string().nullish(),
																				lastModified: zod.iso.datetime({ offset: true }).nullish(),
																				lastModifiedBy: zod.string().nullish(),
																				id: zod.int(),
																				contractId: zod.int(),
																				contract: zod.unknown(),
																				contractConfigId: zod.int(),
																				contractField: zod.unknown(),
																				isActive: zod.boolean(),
																			})
																		),
																	})
																),
															}),
														}),
														startDate: zod.iso.datetime({ offset: true }),
														endDate: zod.iso.datetime({ offset: true }).nullish(),
														price: zod.number(),
														isActive: zod.boolean(),
														userId: zod.string(),
														user: zod.unknown(),
													})
												),
												userRoles: zod.array(
													zod.object({
														userId: zod.string(),
														roleId: zod.string(),
														id: zod.int(),
														facilityId: zod.int().nullish(),
														facility: zod.unknown().nullish(),
														role: zod.object({
															id: zod.string(),
															name: zod.string().nullish(),
															normalizedName: zod.string().nullish(),
															concurrencyStamp: zod.string().nullish(),
														}),
													})
												),
												lastSync: zod.iso.datetime({ offset: true }),
											})
											.nullish(),
										isPaid: zod.boolean(),
										amountOutstanding: zod.number(),
										amountPaid: zod.number(),
										expiresAt: zod.iso.datetime({ offset: true }),
										slotContractBookings: zod.array(
											zod.object({
												id: zod.int(),
												slotContractId: zod.int(),
												slotContract: zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													slotId: zod.string(),
													slot: zod.unknown(),
													contractId: zod.int(),
													contract: zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														name: zod.string(),
														businessId: zod.int(),
														business: zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															name: zod.string(),
															outlets: zod.array(zod.unknown()),
															contracts: zod.array(zod.unknown()),
															contractFields: zod.array(
																zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	name: zod.string(),
																	fieldValidation: zod.string().nullish(),
																	businessId: zod.int(),
																	business: zod.unknown(),
																	contractFieldConfigs: zod.array(
																		zod.object({
																			created: zod.iso.datetime({ offset: true }),
																			createdBy: zod.string().nullish(),
																			lastModified: zod.iso.datetime({ offset: true }).nullish(),
																			lastModifiedBy: zod.string().nullish(),
																			id: zod.int(),
																			contractId: zod.int(),
																			contract: zod.unknown(),
																			contractConfigId: zod.int(),
																			contractField: zod.unknown(),
																			isActive: zod.boolean(),
																		})
																	),
																})
															),
														}),
													}),
													price: zod.number(),
													validationId: zod.int().nullish(),
													validation: zod
														.object({
															id: zod.int(),
															name: zod.string(),
														})
														.nullish(),
													canPayLater: zod.boolean(),
													description: zod.string().nullish(),
												}),
												bookingId: zod.int(),
												booking: zod.unknown(),
												userId: zod.string().nullish(),
												name: zod.string().nullish(),
												email: zod.string().nullish(),
												cellphone: zod.string().nullish(),
											})
										),
										extraBookings: zod.array(zod.unknown()),
									}),
									amount: zod.int(),
								})
							),
						})
					),
					paymentProviderConfigs: zod.array(
						zod.object({
							created: zod.iso.datetime({ offset: true }),
							createdBy: zod.string().nullish(),
							lastModified: zod.iso.datetime({ offset: true }).nullish(),
							lastModifiedBy: zod.string().nullish(),
							id: zod.int(),
							facilityId: zod.int(),
							facility: zod.unknown(),
							providerKey: zod.string(),
							type: zod.union([zod.literal(0), zod.literal(1)]),
							iv: zod.string(),
							encryptedSettings: zod.string(),
							enabled: zod.boolean(),
						})
					),
				})
			),
			extras: zod.array(
				zod.object({
					id: zod.int(),
					facilityId: zod.int(),
					facility: zod.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.int(),
						name: zod.string(),
						outletId: zod.int(),
						outlet: zod.unknown(),
						isActive: zod.boolean().nullish(),
						facilityTypeId: zod.int(),
						contact: zod.string().nullish(),
						email: zod.string().nullish(),
						rules: zod.string().nullish(),
						operatingHours: zod.string().nullish(),
						facilityType: zod.object({
							id: zod.int(),
							name: zod.string(),
						}),
						resources: zod.array(
							zod.object({
								created: zod.iso.datetime({ offset: true }),
								createdBy: zod.string().nullish(),
								lastModified: zod.iso.datetime({ offset: true }).nullish(),
								lastModifiedBy: zod.string().nullish(),
								id: zod.int(),
								name: zod.string(),
								facilityId: zod.int(),
								facility: zod.unknown(),
								isActive: zod.boolean(),
								slots: zod.array(
									zod.object({
										created: zod.iso.datetime({ offset: true }),
										createdBy: zod.string().nullish(),
										lastModified: zod.iso.datetime({ offset: true }).nullish(),
										lastModifiedBy: zod.string().nullish(),
										id: zod.string(),
										resourceId: zod.int().nullish(),
										resource: zod.unknown().nullish(),
										facilityId: zod.int().nullish(),
										facility: zod.unknown().nullish(),
										startDatetime: zod.iso.datetime({ offset: true }),
										endDatetime: zod.iso.datetime({ offset: true }).nullish(),
										maxBookings: zod.int(),
										slotContracts: zod.array(
											zod.object({
												created: zod.iso.datetime({ offset: true }),
												createdBy: zod.string().nullish(),
												lastModified: zod.iso.datetime({ offset: true }).nullish(),
												lastModifiedBy: zod.string().nullish(),
												id: zod.int(),
												slotId: zod.string(),
												slot: zod.unknown(),
												contractId: zod.int(),
												contract: zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													name: zod.string(),
													businessId: zod.int(),
													business: zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														name: zod.string(),
														outlets: zod.array(zod.unknown()),
														contracts: zod.array(zod.unknown()),
														contractFields: zod.array(
															zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																name: zod.string(),
																fieldValidation: zod.string().nullish(),
																businessId: zod.int(),
																business: zod.unknown(),
																contractFieldConfigs: zod.array(
																	zod.object({
																		created: zod.iso.datetime({ offset: true }),
																		createdBy: zod.string().nullish(),
																		lastModified: zod.iso.datetime({ offset: true }).nullish(),
																		lastModifiedBy: zod.string().nullish(),
																		id: zod.int(),
																		contractId: zod.int(),
																		contract: zod.unknown(),
																		contractConfigId: zod.int(),
																		contractField: zod.unknown(),
																		isActive: zod.boolean(),
																	})
																),
															})
														),
													}),
												}),
												price: zod.number(),
												validationId: zod.int().nullish(),
												validation: zod
													.object({
														id: zod.int(),
														name: zod.string(),
													})
													.nullish(),
												canPayLater: zod.boolean(),
												description: zod.string().nullish(),
											})
										),
										extraBookings: zod.array(
											zod.object({
												extraId: zod.int(),
												extra: zod.unknown(),
												bookingId: zod.int(),
												booking: zod.object({
													created: zod.iso.datetime({ offset: true }),
													createdBy: zod.string().nullish(),
													lastModified: zod.iso.datetime({ offset: true }).nullish(),
													lastModifiedBy: zod.string().nullish(),
													id: zod.int(),
													bookingStatusId: zod.int(),
													bookingStatus: zod.object({
														id: zod.int(),
														name: zod.string(),
													}),
													bookingStatusDate: zod.iso.datetime({ offset: true }),
													userId: zod.string().nullish(),
													user: zod
														.object({
															id: zod.string(),
															userName: zod.string().nullish(),
															normalizedUserName: zod.string().nullish(),
															email: zod.string().nullish(),
															normalizedEmail: zod.string().nullish(),
															emailConfirmed: zod.boolean(),
															passwordHash: zod.string().nullish(),
															securityStamp: zod.string().nullish(),
															concurrencyStamp: zod.string().nullish(),
															phoneNumber: zod.string().nullish(),
															phoneNumberConfirmed: zod.boolean(),
															twoFactorEnabled: zod.boolean(),
															lockoutEnd: zod.iso.datetime({ offset: true }).nullish(),
															lockoutEnabled: zod.boolean(),
															accessFailedCount: zod.int(),
															firstName: zod.string(),
															lastName: zod.string(),
															picture: zod.string().nullish(),
															userContracts: zod.array(
																zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	contractId: zod.int(),
																	contract: zod.object({
																		created: zod.iso.datetime({ offset: true }),
																		createdBy: zod.string().nullish(),
																		lastModified: zod.iso.datetime({ offset: true }).nullish(),
																		lastModifiedBy: zod.string().nullish(),
																		id: zod.int(),
																		name: zod.string(),
																		businessId: zod.int(),
																		business: zod.object({
																			created: zod.iso.datetime({ offset: true }),
																			createdBy: zod.string().nullish(),
																			lastModified: zod.iso.datetime({ offset: true }).nullish(),
																			lastModifiedBy: zod.string().nullish(),
																			id: zod.int(),
																			name: zod.string(),
																			outlets: zod.array(zod.unknown()),
																			contracts: zod.array(zod.unknown()),
																			contractFields: zod.array(
																				zod.object({
																					created: zod.iso.datetime({ offset: true }),
																					createdBy: zod.string().nullish(),
																					lastModified: zod.iso.datetime({ offset: true }).nullish(),
																					lastModifiedBy: zod.string().nullish(),
																					id: zod.int(),
																					name: zod.string(),
																					fieldValidation: zod.string().nullish(),
																					businessId: zod.int(),
																					business: zod.unknown(),
																					contractFieldConfigs: zod.array(
																						zod.object({
																							created: zod.iso.datetime({ offset: true }),
																							createdBy: zod.string().nullish(),
																							lastModified: zod.iso.datetime({ offset: true }).nullish(),
																							lastModifiedBy: zod.string().nullish(),
																							id: zod.int(),
																							contractId: zod.int(),
																							contract: zod.unknown(),
																							contractConfigId: zod.int(),
																							contractField: zod.unknown(),
																							isActive: zod.boolean(),
																						})
																					),
																				})
																			),
																		}),
																	}),
																	startDate: zod.iso.datetime({ offset: true }),
																	endDate: zod.iso.datetime({ offset: true }).nullish(),
																	price: zod.number(),
																	isActive: zod.boolean(),
																	userId: zod.string(),
																	user: zod.unknown(),
																})
															),
															userRoles: zod.array(
																zod.object({
																	userId: zod.string(),
																	roleId: zod.string(),
																	id: zod.int(),
																	facilityId: zod.int().nullish(),
																	facility: zod.unknown().nullish(),
																	role: zod.object({
																		id: zod.string(),
																		name: zod.string().nullish(),
																		normalizedName: zod.string().nullish(),
																		concurrencyStamp: zod.string().nullish(),
																	}),
																})
															),
															lastSync: zod.iso.datetime({ offset: true }),
														})
														.nullish(),
													isPaid: zod.boolean(),
													amountOutstanding: zod.number(),
													amountPaid: zod.number(),
													expiresAt: zod.iso.datetime({ offset: true }),
													slotContractBookings: zod.array(
														zod.object({
															id: zod.int(),
															slotContractId: zod.int(),
															slotContract: zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																slotId: zod.string(),
																slot: zod.unknown(),
																contractId: zod.int(),
																contract: zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	name: zod.string(),
																	businessId: zod.int(),
																	business: zod.object({
																		created: zod.iso.datetime({ offset: true }),
																		createdBy: zod.string().nullish(),
																		lastModified: zod.iso.datetime({ offset: true }).nullish(),
																		lastModifiedBy: zod.string().nullish(),
																		id: zod.int(),
																		name: zod.string(),
																		outlets: zod.array(zod.unknown()),
																		contracts: zod.array(zod.unknown()),
																		contractFields: zod.array(
																			zod.object({
																				created: zod.iso.datetime({ offset: true }),
																				createdBy: zod.string().nullish(),
																				lastModified: zod.iso.datetime({ offset: true }).nullish(),
																				lastModifiedBy: zod.string().nullish(),
																				id: zod.int(),
																				name: zod.string(),
																				fieldValidation: zod.string().nullish(),
																				businessId: zod.int(),
																				business: zod.unknown(),
																				contractFieldConfigs: zod.array(
																					zod.object({
																						created: zod.iso.datetime({ offset: true }),
																						createdBy: zod.string().nullish(),
																						lastModified: zod.iso.datetime({ offset: true }).nullish(),
																						lastModifiedBy: zod.string().nullish(),
																						id: zod.int(),
																						contractId: zod.int(),
																						contract: zod.unknown(),
																						contractConfigId: zod.int(),
																						contractField: zod.unknown(),
																						isActive: zod.boolean(),
																					})
																				),
																			})
																		),
																	}),
																}),
																price: zod.number(),
																validationId: zod.int().nullish(),
																validation: zod
																	.object({
																		id: zod.int(),
																		name: zod.string(),
																	})
																	.nullish(),
																canPayLater: zod.boolean(),
																description: zod.string().nullish(),
															}),
															bookingId: zod.int(),
															booking: zod.unknown(),
															userId: zod.string().nullish(),
															name: zod.string().nullish(),
															email: zod.string().nullish(),
															cellphone: zod.string().nullish(),
														})
													),
													extraBookings: zod.array(zod.unknown()),
												}),
												amount: zod.int(),
											})
										),
									})
								),
							})
						),
						slots: zod.array(
							zod.object({
								created: zod.iso.datetime({ offset: true }),
								createdBy: zod.string().nullish(),
								lastModified: zod.iso.datetime({ offset: true }).nullish(),
								lastModifiedBy: zod.string().nullish(),
								id: zod.string(),
								resourceId: zod.int().nullish(),
								resource: zod
									.object({
										created: zod.iso.datetime({ offset: true }),
										createdBy: zod.string().nullish(),
										lastModified: zod.iso.datetime({ offset: true }).nullish(),
										lastModifiedBy: zod.string().nullish(),
										id: zod.int(),
										name: zod.string(),
										facilityId: zod.int(),
										facility: zod.unknown(),
										isActive: zod.boolean(),
										slots: zod.array(zod.unknown()),
									})
									.nullish(),
								facilityId: zod.int().nullish(),
								facility: zod.unknown().nullish(),
								startDatetime: zod.iso.datetime({ offset: true }),
								endDatetime: zod.iso.datetime({ offset: true }).nullish(),
								maxBookings: zod.int(),
								slotContracts: zod.array(
									zod.object({
										created: zod.iso.datetime({ offset: true }),
										createdBy: zod.string().nullish(),
										lastModified: zod.iso.datetime({ offset: true }).nullish(),
										lastModifiedBy: zod.string().nullish(),
										id: zod.int(),
										slotId: zod.string(),
										slot: zod.unknown(),
										contractId: zod.int(),
										contract: zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											name: zod.string(),
											businessId: zod.int(),
											business: zod.object({
												created: zod.iso.datetime({ offset: true }),
												createdBy: zod.string().nullish(),
												lastModified: zod.iso.datetime({ offset: true }).nullish(),
												lastModifiedBy: zod.string().nullish(),
												id: zod.int(),
												name: zod.string(),
												outlets: zod.array(zod.unknown()),
												contracts: zod.array(zod.unknown()),
												contractFields: zod.array(
													zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														name: zod.string(),
														fieldValidation: zod.string().nullish(),
														businessId: zod.int(),
														business: zod.unknown(),
														contractFieldConfigs: zod.array(
															zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																contractId: zod.int(),
																contract: zod.unknown(),
																contractConfigId: zod.int(),
																contractField: zod.unknown(),
																isActive: zod.boolean(),
															})
														),
													})
												),
											}),
										}),
										price: zod.number(),
										validationId: zod.int().nullish(),
										validation: zod
											.object({
												id: zod.int(),
												name: zod.string(),
											})
											.nullish(),
										canPayLater: zod.boolean(),
										description: zod.string().nullish(),
									})
								),
								extraBookings: zod.array(
									zod.object({
										extraId: zod.int(),
										extra: zod.unknown(),
										bookingId: zod.int(),
										booking: zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											bookingStatusId: zod.int(),
											bookingStatus: zod.object({
												id: zod.int(),
												name: zod.string(),
											}),
											bookingStatusDate: zod.iso.datetime({ offset: true }),
											userId: zod.string().nullish(),
											user: zod
												.object({
													id: zod.string(),
													userName: zod.string().nullish(),
													normalizedUserName: zod.string().nullish(),
													email: zod.string().nullish(),
													normalizedEmail: zod.string().nullish(),
													emailConfirmed: zod.boolean(),
													passwordHash: zod.string().nullish(),
													securityStamp: zod.string().nullish(),
													concurrencyStamp: zod.string().nullish(),
													phoneNumber: zod.string().nullish(),
													phoneNumberConfirmed: zod.boolean(),
													twoFactorEnabled: zod.boolean(),
													lockoutEnd: zod.iso.datetime({ offset: true }).nullish(),
													lockoutEnabled: zod.boolean(),
													accessFailedCount: zod.int(),
													firstName: zod.string(),
													lastName: zod.string(),
													picture: zod.string().nullish(),
													userContracts: zod.array(
														zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															contractId: zod.int(),
															contract: zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																name: zod.string(),
																businessId: zod.int(),
																business: zod.object({
																	created: zod.iso.datetime({ offset: true }),
																	createdBy: zod.string().nullish(),
																	lastModified: zod.iso.datetime({ offset: true }).nullish(),
																	lastModifiedBy: zod.string().nullish(),
																	id: zod.int(),
																	name: zod.string(),
																	outlets: zod.array(zod.unknown()),
																	contracts: zod.array(zod.unknown()),
																	contractFields: zod.array(
																		zod.object({
																			created: zod.iso.datetime({ offset: true }),
																			createdBy: zod.string().nullish(),
																			lastModified: zod.iso.datetime({ offset: true }).nullish(),
																			lastModifiedBy: zod.string().nullish(),
																			id: zod.int(),
																			name: zod.string(),
																			fieldValidation: zod.string().nullish(),
																			businessId: zod.int(),
																			business: zod.unknown(),
																			contractFieldConfigs: zod.array(
																				zod.object({
																					created: zod.iso.datetime({ offset: true }),
																					createdBy: zod.string().nullish(),
																					lastModified: zod.iso.datetime({ offset: true }).nullish(),
																					lastModifiedBy: zod.string().nullish(),
																					id: zod.int(),
																					contractId: zod.int(),
																					contract: zod.unknown(),
																					contractConfigId: zod.int(),
																					contractField: zod.unknown(),
																					isActive: zod.boolean(),
																				})
																			),
																		})
																	),
																}),
															}),
															startDate: zod.iso.datetime({ offset: true }),
															endDate: zod.iso.datetime({ offset: true }).nullish(),
															price: zod.number(),
															isActive: zod.boolean(),
															userId: zod.string(),
															user: zod.unknown(),
														})
													),
													userRoles: zod.array(
														zod.object({
															userId: zod.string(),
															roleId: zod.string(),
															id: zod.int(),
															facilityId: zod.int().nullish(),
															facility: zod.unknown().nullish(),
															role: zod.object({
																id: zod.string(),
																name: zod.string().nullish(),
																normalizedName: zod.string().nullish(),
																concurrencyStamp: zod.string().nullish(),
															}),
														})
													),
													lastSync: zod.iso.datetime({ offset: true }),
												})
												.nullish(),
											isPaid: zod.boolean(),
											amountOutstanding: zod.number(),
											amountPaid: zod.number(),
											expiresAt: zod.iso.datetime({ offset: true }),
											slotContractBookings: zod.array(
												zod.object({
													id: zod.int(),
													slotContractId: zod.int(),
													slotContract: zod.object({
														created: zod.iso.datetime({ offset: true }),
														createdBy: zod.string().nullish(),
														lastModified: zod.iso.datetime({ offset: true }).nullish(),
														lastModifiedBy: zod.string().nullish(),
														id: zod.int(),
														slotId: zod.string(),
														slot: zod.unknown(),
														contractId: zod.int(),
														contract: zod.object({
															created: zod.iso.datetime({ offset: true }),
															createdBy: zod.string().nullish(),
															lastModified: zod.iso.datetime({ offset: true }).nullish(),
															lastModifiedBy: zod.string().nullish(),
															id: zod.int(),
															name: zod.string(),
															businessId: zod.int(),
															business: zod.object({
																created: zod.iso.datetime({ offset: true }),
																createdBy: zod.string().nullish(),
																lastModified: zod.iso.datetime({ offset: true }).nullish(),
																lastModifiedBy: zod.string().nullish(),
																id: zod.int(),
																name: zod.string(),
																outlets: zod.array(zod.unknown()),
																contracts: zod.array(zod.unknown()),
																contractFields: zod.array(
																	zod.object({
																		created: zod.iso.datetime({ offset: true }),
																		createdBy: zod.string().nullish(),
																		lastModified: zod.iso.datetime({ offset: true }).nullish(),
																		lastModifiedBy: zod.string().nullish(),
																		id: zod.int(),
																		name: zod.string(),
																		fieldValidation: zod.string().nullish(),
																		businessId: zod.int(),
																		business: zod.unknown(),
																		contractFieldConfigs: zod.array(
																			zod.object({
																				created: zod.iso.datetime({ offset: true }),
																				createdBy: zod.string().nullish(),
																				lastModified: zod.iso.datetime({ offset: true }).nullish(),
																				lastModifiedBy: zod.string().nullish(),
																				id: zod.int(),
																				contractId: zod.int(),
																				contract: zod.unknown(),
																				contractConfigId: zod.int(),
																				contractField: zod.unknown(),
																				isActive: zod.boolean(),
																			})
																		),
																	})
																),
															}),
														}),
														price: zod.number(),
														validationId: zod.int().nullish(),
														validation: zod
															.object({
																id: zod.int(),
																name: zod.string(),
															})
															.nullish(),
														canPayLater: zod.boolean(),
														description: zod.string().nullish(),
													}),
													bookingId: zod.int(),
													booking: zod.unknown(),
													userId: zod.string().nullish(),
													name: zod.string().nullish(),
													email: zod.string().nullish(),
													cellphone: zod.string().nullish(),
												})
											),
											extraBookings: zod.array(zod.unknown()),
										}),
										amount: zod.int(),
									})
								),
							})
						),
						paymentProviderConfigs: zod.array(
							zod.object({
								created: zod.iso.datetime({ offset: true }),
								createdBy: zod.string().nullish(),
								lastModified: zod.iso.datetime({ offset: true }).nullish(),
								lastModifiedBy: zod.string().nullish(),
								id: zod.int(),
								facilityId: zod.int(),
								facility: zod.unknown(),
								providerKey: zod.string(),
								type: zod.union([zod.literal(0), zod.literal(1)]),
								iv: zod.string(),
								encryptedSettings: zod.string(),
								enabled: zod.boolean(),
							})
						),
					}),
					outletId: zod.int(),
					name: zod.string(),
					code: zod.string(),
					price: zod.number(),
					isAvailable: zod.boolean(),
					isOnline: zod.boolean(),
				})
			),
			contractOutlets: zod.array(
				zod.object({
					created: zod.iso.datetime({ offset: true }),
					createdBy: zod.string().nullish(),
					lastModified: zod.iso.datetime({ offset: true }).nullish(),
					lastModifiedBy: zod.string().nullish(),
					id: zod.int(),
					contractId: zod.int(),
					contract: zod.object({
						created: zod.iso.datetime({ offset: true }),
						createdBy: zod.string().nullish(),
						lastModified: zod.iso.datetime({ offset: true }).nullish(),
						lastModifiedBy: zod.string().nullish(),
						id: zod.int(),
						name: zod.string(),
						businessId: zod.int(),
						business: zod.object({
							created: zod.iso.datetime({ offset: true }),
							createdBy: zod.string().nullish(),
							lastModified: zod.iso.datetime({ offset: true }).nullish(),
							lastModifiedBy: zod.string().nullish(),
							id: zod.int(),
							name: zod.string(),
							outlets: zod.array(zod.unknown()),
							contracts: zod.array(zod.unknown()),
							contractFields: zod.array(
								zod.object({
									created: zod.iso.datetime({ offset: true }),
									createdBy: zod.string().nullish(),
									lastModified: zod.iso.datetime({ offset: true }).nullish(),
									lastModifiedBy: zod.string().nullish(),
									id: zod.int(),
									name: zod.string(),
									fieldValidation: zod.string().nullish(),
									businessId: zod.int(),
									business: zod.unknown(),
									contractFieldConfigs: zod.array(
										zod.object({
											created: zod.iso.datetime({ offset: true }),
											createdBy: zod.string().nullish(),
											lastModified: zod.iso.datetime({ offset: true }).nullish(),
											lastModifiedBy: zod.string().nullish(),
											id: zod.int(),
											contractId: zod.int(),
											contract: zod.unknown(),
											contractConfigId: zod.int(),
											contractField: zod.unknown(),
											isActive: zod.boolean(),
										})
									),
								})
							),
						}),
					}),
					outletId: zod.int(),
					outlet: zod.unknown(),
					contractStart: zod.iso.datetime({ offset: true }).nullish(),
					contractEnd: zod.iso.datetime({ offset: true }).nullish(),
					isActive: zod.boolean(),
				})
			),
		})
	),
	pageNumber: zod.int(),
	totalPages: zod.int(),
	totalCount: zod.int(),
	hasPreviousPage: zod.boolean(),
	hasNextPage: zod.boolean(),
});

export const OutletGetParams = zod.object({
	slug: zod.string(),
});

export const OutletGetResponse = zod.object({
	id: zod.int(),
	slug: zod.string(),
	name: zod.string(),
	businessId: zod.int(),
	business: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	vatNumber: zod.string(),
	logo: zod.string().nullish(),
	address: zod.string().nullish(),
	company: zod.string().nullish(),
	description: zod.string().nullish(),
	registration: zod.string().nullish(),
	tags: zod.string().nullish(),
	contact: zod.string().nullish(),
	email: zod.string().nullish(),
	operatingHours: zod.string().nullish(),
	displayName: zod.string(),
	outletTypeId: zod.int(),
	outletType: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	isActive: zod.boolean(),
	facilities: zod.array(
		zod.object({
			id: zod.int(),
			name: zod.string(),
			outletId: zod.int(),
			isActive: zod.boolean().nullish(),
			facilityTypeId: zod.int(),
			facilityType: zod.object({
				id: zod.int(),
				name: zod.string(),
			}),
			contact: zod.string().nullish(),
			email: zod.string().nullish(),
			rules: zod.string().nullish(),
			operatingHours: zod.string().nullish(),
		})
	),
});

export const OutletAdminGetParams = zod.object({
	slug: zod.string(),
});

export const OutletAdminGetResponse = zod.object({
	id: zod.int(),
	slug: zod.string(),
	name: zod.string(),
	businessId: zod.int(),
	business: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	vatNumber: zod.string(),
	logo: zod.string().nullish(),
	address: zod.string().nullish(),
	company: zod.string().nullish(),
	description: zod.string().nullish(),
	registration: zod.string().nullish(),
	tags: zod.string().nullish(),
	contact: zod.string().nullish(),
	email: zod.string().nullish(),
	operatingHours: zod.string().nullish(),
	displayName: zod.string(),
	outletTypeId: zod.int(),
	outletType: zod.object({
		id: zod.int(),
		name: zod.string(),
	}),
	isActive: zod.boolean(),
	facilities: zod.array(
		zod.object({
			id: zod.int(),
			name: zod.string(),
			outletId: zod.int(),
			isActive: zod.boolean().nullish(),
			facilityTypeId: zod.int(),
			facilityType: zod.object({
				id: zod.int(),
				name: zod.string(),
			}),
			contact: zod.string().nullish(),
			email: zod.string().nullish(),
			rules: zod.string().nullish(),
			operatingHours: zod.string().nullish(),
		})
	),
});
