/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PaymentResultGetParams = zod.object({
	provider: zod.string(),
});

export const PaymentResultGetResponse = zod.void();

export const PaymentResultPostParams = zod.object({
	provider: zod.string(),
});

export const PaymentResultPostResponse = zod.void();

export const PaymentInitiateBody = zod.object({
	bookingId: zod.int(),
	providerName: zod.string(),
});

export const PaymentInitiateResponse = zod.object({
	transactionId: zod.string(),
	redirectUrl: zod.string(),
	providerReference: zod.string().nullish(),
});

export const PaymentFormParams = zod.object({
	provider: zod.string(),
	transactionId: zod.string(),
});

export const PaymentFormResponse = zod.void();

export const PaymentCheckoutParams = zod.object({
	provider: zod.string(),
});

export const PaymentCheckoutBody = zod.object({
	amount: zod.number(),
	currency: zod.string(),
	transactionId: zod.string(),
	description: zod.string().nullish(),
});

export const PaymentCheckoutResponse = zod.object({
	success: zod.boolean(),
	transactionId: zod.string(),
	providerReference: zod.string().nullish(),
	redirectUrl: zod.string().nullish(),
	formActionUrl: zod.string().nullish(),
	formFields: zod.record(zod.string(), zod.string()).nullish(),
	status: zod.string().nullish(),
	errorMessage: zod.string().nullish(),
});
