/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PaymentVouchersParams = zod.object({
	bookingId: zod.int(),
});

export const PaymentVouchersResponseItem = zod.object({
	grantId: zod.string(),
	voucherId: zod.int(),
	name: zod.string(),
	description: zod.string(),
	isExtra: zod.boolean(),
	redemptionKind: zod.enum({
		Entitlement: 1,
		Credit: 2,
		Discount: 3,
	}),
	discountMode: zod
		.enum({
			Percentage: 1,
			FixedAmount: 2,
		})
		.nullish(),
	discountValue: zod.number().nullish(),
	maxDiscountAmount: zod.number().nullish(),
	amountRemaining: zod.number(),
	expiryDate: zod.iso.datetime({ offset: true }),
	isEligible: zod.boolean(),
	ineligibleReason: zod.string().nullish(),
	eligibleAmount: zod.number(),
	paymentValue: zod.number(),
	targets: zod.array(
		zod.object({
			slotContractBookingId: zod.int().nullish(),
			extraId: zod.int().nullish(),
			name: zod.string(),
			unitsAvailable: zod.int(),
			unitPrice: zod.number(),
		})
	),
});
export const PaymentVouchersResponse = zod.array(PaymentVouchersResponseItem);

export const PaymentVoucherBody = zod.object({
	bookingId: zod.int(),
	grantId: zod.string(),
	slotContractBookingId: zod.int().nullish(),
	extraId: zod.int().nullish(),
	quantity: zod.int(),
});

export const PaymentVoucherResponse = zod.object({
	transactionId: zod.string(),
	amount: zod.number(),
	paymentStatusId: zod.int(),
	amountPaid: zod.number(),
	amountOutstanding: zod.number(),
	isPaid: zod.boolean(),
});

export const PaymentResultGetParams = zod.object({
	provider: zod.string(),
});

export const PaymentResultGetResponse = zod.void();

export const PaymentResultPostParams = zod.object({
	provider: zod.string(),
});

export const PaymentResultPostResponse = zod.void();

export const PaymentInitiateBody = zod.object({
	bookingId: zod.int(),
	providerName: zod.string(),
	amount: zod.number().nullish(),
	recurring: zod
		.object({
			frequency: zod.enum({
				Monthly: 3,
				Quarterly: 4,
				Biannually: 5,
				Annually: 6,
			}),
			cycles: zod.int(),
			recurringAmount: zod.number().nullish(),
			firstBillingDate: zod.iso.date().nullish(),
		})
		.nullish(),
});

export const PaymentInitiateResponse = zod.object({
	transactionId: zod.string(),
	redirectUrl: zod.string(),
	providerReference: zod.string().nullish(),
});

export const PaymentGetBookingParams = zod.object({
	bookingId: zod.int(),
});

export const PaymentGetBookingResponse = zod.object({
	bookingId: zod.int(),
	amountPaid: zod.number(),
	amountOutstanding: zod.number(),
	amountAvailable: zod.number(),
	isPaid: zod.boolean(),
	payments: zod.array(
		zod.object({
			id: zod.int(),
			transactionId: zod.string(),
			amount: zod.number(),
			paymentTypeId: zod.int(),
			paymentType: zod.string(),
			paymentStatusId: zod.int(),
			paymentStatus: zod.string(),
			providerName: zod.string(),
			paymentStatusDate: zod.iso.datetime({ offset: true }),
		})
	),
});

export const PaymentFormParams = zod.object({
	provider: zod.string(),
	transactionId: zod.string(),
});

export const PaymentFormResponse = zod.void();

export const PaymentCheckoutParams = zod.object({
	provider: zod.string(),
});

export const PaymentCheckoutBody = zod.object({
	amount: zod.number(),
	currency: zod.string(),
	transactionId: zod.string(),
	description: zod.string().nullish(),
});

export const PaymentCheckoutResponse = zod.object({
	success: zod.boolean(),
	transactionId: zod.string(),
	providerReference: zod.string().nullish(),
	redirectUrl: zod.string().nullish(),
	formActionUrl: zod.string().nullish(),
	formFields: zod.record(zod.string(), zod.string()).nullish(),
	status: zod.string().nullish(),
	errorMessage: zod.string().nullish(),
});
