/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const SlotGetContractsParams = zod.object({
	id: zod.string(),
});

export const SlotGetContractsResponseItem = zod.object({
	id: zod.int(),
	slotId: zod.string(),
	contractId: zod.int(),
	contractName: zod.string(),
	price: zod.number(),
	validationId: zod.int().nullish(),
	canPayLater: zod.boolean(),
	description: zod.string().nullish(),
});
export const SlotGetContractsResponse = zod.array(SlotGetContractsResponseItem);

export const SlotGetAllQueryParams = zod.object({
	facilityId: zod.int(),
	date: zod.iso.datetime({ offset: true }),
});

export const SlotGetAllResponseItem = zod.object({
	id: zod.string(),
	facilityId: zod.int().nullish(),
	resourceId: zod.int().nullish(),
	resourceName: zod.string().nullish(),
	startDatetime: zod.iso.datetime({ offset: true }),
	endDatetime: zod.iso.datetime({ offset: true }).nullish(),
	booked: zod.int(),
	total: zod.int(),
	isEnabled: zod.boolean(),
	isAvailable: zod.boolean(),
});
export const SlotGetAllResponse = zod.array(SlotGetAllResponseItem);

export const SlotAvailableBody = zod.object({
	id: zod.string(),
	slotCount: zod.int().nullish(),
});

export const SlotAvailableResponse = zod.boolean();
