/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const TestAnotherResponse = zod.void();

export const TestQueryParams = zod.object({
	name: zod.string(),
});

export const TestResponse = zod.object({
	success: zod.boolean(),
	token: zod.string().nullish(),
	other: zod.unknown().nullish(),
});
