/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Club.Api
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const WalletVouchersResponseItem = zod.object({
	grantId: zod.string(),
	voucherId: zod.int(),
	name: zod.string(),
	description: zod.string(),
	isExtra: zod.boolean(),
	redemptionKind: zod.enum({
		Entitlement: 1,
		Credit: 2,
		Discount: 3,
	}),
	discountMode: zod
		.enum({
			Percentage: 1,
			FixedAmount: 2,
		})
		.nullish(),
	discountValue: zod.number().nullish(),
	maxDiscountAmount: zod.number().nullish(),
	amountGranted: zod.number(),
	amountRemaining: zod.number(),
	grantedAt: zod.iso.datetime({ offset: true }),
	expiryDate: zod.iso.datetime({ offset: true }),
	currency: zod.string(),
	isWalletActive: zod.boolean(),
	facilityNames: zod.array(zod.string()),
	gameTypes: zod.array(zod.string()),
	extraNames: zod.array(zod.string()),
});
export const WalletVouchersResponse = zod.array(WalletVouchersResponseItem);
